#!/usr/bin/bash

# Script to check the coding style. Currently only checks #0.

only_show_failed=false

for flag in $@
do
    if [[ "$flag" -eq "-f" ]]
    then
        only_show_failed=true
    fi
done

for file in $(find . -name *.h)
do
    if [[ "$(grep LIBSAPLING_ $file | wc -l)" -eq 2 ]]
    then
        if [[ "$only_show_failed" = false ]]
        then
            tput setaf 2
            echo -n "[OK]"
            tput init
            echo " $file"
        fi
    else
        tput setaf 1
        echo "[FAILED] $file { 0 }"
        tput init
    fi
done
